name: Selenium

on:
  workflow_call:
    inputs:
      server:
        required: true
        type: string
        description: Select server to test

  workflow_dispatch:
    inputs:
      server:
        type: choice
        description: Select server to test
        options:
          - stage.site.local
          - site.local

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Selected server
        shell: bash
        run: echo ${{ inputs.server }}
        
      - name: Trigger Jenkins Job
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: ${{ secrets.JENKINS_HOST }}
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.JENKINS_TOKEN }}
          job_name: "site_site"
          job_timeout: "600"
          job_params: |
            {
              "URL": "https://${{ inputs.server }}"
            }
